name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Use node 17.0
        uses: actions/setup-node@v2
        with:
          node-version: 17.0.0
      - name: Install dependencies
        run: npm ci
      - name: Rund tests
        run: npm run test:unit


